version: "3"

services:
  backend:
    image: frappe/erpnext:v15.65.4
    networks:
      - frappe_network
    restart: unless-stopped
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin

  configurator:
    image: frappe/erpnext:v15.65.4
    networks:
      - frappe_network
    restart: "no"
    entrypoint: ["bash", "-c"]
    command: >
      ls -1 apps > sites/apps.txt &&
      bench set-config -g db_host db &&
      bench set-config -gp db_port 3306 &&
      bench set-config -g redis_cache redis://redis-cache:6379 &&
      bench set-config -g redis_queue redis://redis-queue:6379 &&
      bench set-config -g redis_socketio redis://redis-queue:6379 &&
      bench set-config -gp socketio_port 9000
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  create-site:
    image: frappe/erpnext:v15.65.4
    networks:
      - frappe_network
    restart: "no"
    entrypoint: ["bash", "-c"]
    command: >
      wait-for-it -t 120 db:3306 &&
      wait-for-it -t 120 redis-cache:6379 &&
      wait-for-it -t 120 redis-queue:6379 &&
      export start=$(date +%s) &&
      until grep -hs ^ sites/common_site_config.json | jq -e '.db_host and .redis_cache and .redis_queue'; do
        echo "Waiting for sites/common_site_config.json to be created";
        sleep 5;
        if (( $(date +%s) - start > 120 )); then
          echo "could not find sites/common_site_config.json with required keys";
          exit 1;
        fi
      done &&
      echo "sites/common_site_config.json found" &&
      bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root --db-root-password=admin --install-app erpnext --set-default frontend
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  db:
    image: mariadb:10.6
    networks:
      - frappe_network
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=admin"]
      interval: 1s
      retries: 20
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    image: frappe/erpnext:v15.65.4
    networks:
      - frappe_network
    depends_on:
      - websocket
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.erp.rule=Host(`erp.era-tools.de`)"
      - "traefik.http.routers.erp.entrypoints=web"
      - "traefik.http.routers.erp.entrypoints=websecure"
      - "traefik.http.routers.erp.tls.certresolver=myresolver"
      - "traefik.http.routers.erp.service=erp"
      - "traefik.http.services.erp.loadbalancer.server.port=8020"
    ports:
      - "8020:80"
    command: ["nginx-entrypoint.sh"]
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  scheduler:
    image: frappe/erpnext:v15.65.4
    networks:
      - frappe_network
    restart: unless-stopped
    command: ["bench", "schedule"]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  queue-short:
    image: frappe/erpnext:v15.65.4
    networks:
      - frappe_network
    restart: unless-stopped
    command: ["bench", "worker", "--queue", "short,default"]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  queue-long:
    image: frappe/erpnext:v15.65.4
    networks:
      - frappe_network
    restart: unless-stopped
    command: ["bench", "worker", "--queue", "long,default,short"]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  websocket:
    image: frappe/erpnext:v15.65.4
    networks:
      - frappe_network
    restart: unless-stopped
    command: ["node", "/home/frappe/frappe-bench/apps/frappe/socketio.js"]
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  redis-cache:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    restart: unless-stopped

  redis-queue:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    restart: unless-stopped
    volumes:
      - redis-queue-data:/data

volumes:
  db-data:
  redis-queue-data:
  sites:
  logs:

networks:
  frappe_network:
    driver: bridge
